# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10,dtype=np.int32)
print(null_vector)

[0 0 0 0 0 0 0 0 0 0]


3. Create a vector with values ranging from 10 to 49

In [3]:
vector1 = np.arange(10,50)
print(vector1tor1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [5]:
print(vector1.shape)

(40,)


5. Print the type of the previous array in question 3

In [6]:
print(vector1.dtype)

int32


6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/workbook/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/workbook/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/workbook/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\

7. Print the dimension of the array in question 3


In [8]:
print(vector1.ndim)

1


8. Create a boolean array with all the True values

In [10]:
boolean_array = np.full((5,),True,dtype=bool)
print(boolean_array)

[ True  True  True  True  True]


9. Create a two dimensional array

In [12]:
two_dim_array = np.zeros((2,2),dtype=np.int32)
print(two_dim_array)

[[0 0]
 [0 0]]


10. Create a three dimensional array



In [14]:
three_dim_array = np.ones((2,2,2),dtype=np.int32)
print(three_dim_array)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [18]:
vector = np.arange(10,20)
print('Original order of vector {0}'.format(vector))
print('Reverse of vector {0}'.format(np.flip(vector)))

Original order of vector [10 11 12 13 14 15 16 17 18 19]
Reverse of vector [19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [19]:
null_vector2 = np.zeros(10,dtype=np.int32)
null_vector2[4] = 1
print(null_vector2)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [20]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1,2,3,4,5])
float_arr=arr.astype(np.float32)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3. 4. 5.]
float32


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [24]:
arr1 = np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
arr3 = arr1*arr2
print(arr3)


[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [87]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

print("arr1 >= arr2")
print(np.greater_equal(arr1, arr2))
print("arr1 > arr2")
print(np.greater(arr1, arr2))
print("arr1 <= arr2")
print(np.less_equal(arr1, arr2))
print("arr1 < arr2")
print(np.less(arr1, arr2))
print("arr1 = arr2")
print(np.equal(arr1, arr2))
print("arr1 != arr2")
print(np.not_equal(arr1, arr2))


arr1 >= arr2
[[ True False  True]
 [False  True False]]
arr1 > arr2
[[ True False  True]
 [False  True False]]
arr1 <= arr2
[[False  True False]
 [ True False  True]]
arr1 < arr2
[[False  True False]
 [ True False  True]]
arr1 = arr2
[[False False False]
 [False False False]]
arr1 != arr2
[[ True  True  True]
 [ True  True  True]]


17. Extract all odd numbers from arr with values(0-9)

In [25]:
_array = np.arange(0,10)
odd_array = _array[_array %2 == 1]
print(odd_array)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [26]:
_array[_array %2 ==1] = -1
print(_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [27]:
arr = np.arange(10)

np.put(arr,range(5,9),12)
print(arr)


[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [29]:
array_with_zeros =np.zeros((5,5),dtype=(np.int32))
array_with_pad = np.pad(array_with_zeros,(1),mode='constant',constant_values=(1))
print(array_with_pad)


[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [12]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] =64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
two_d_array = np.arange(0,9).reshape(3,3)
print(two_d_array[0,:])


[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [41]:
two_d_array_2 = np.arange(0,9).reshape(3,3)
print(two_d_array_2[1,1])

4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [42]:
two_d_array_3 = np.arange(0,9).reshape(3,3)

print(two_d_array_3[:2,2])

[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
two_d_array_4 = np.random.randint(100,size=(10,10))
print(two_d_array_4)
print("Minimum value of 10 X 10 array is {}".format(np.amin(two_d_array_4)))
print("Maximum value of 10 X 10 array is {}".format(np.amax(two_d_array_4)))


[[ 2 89 67 14 45 65 98 13 55 28]
 [39 59  7  4 68 99 73 91 43 65]
 [95 20 55  1 39 91 83 67 51 14]
 [ 9  8 47 13 48 77 92 66 59 87]
 [77 72 12 74 30 55 91 25 61 55]
 [22 19 32 19 31 63  5 47 36 11]
 [38 26 83 61 38 84 48 50 75 80]
 [38 80 27 70 85 91 99 86 30 31]
 [90 48 46 35 72 13 11 13 53 66]
 [67 96 48  4 81 27 65 21 50 91]]
Minimum value of 10 X 10 array is 1
Maximum value of 10 X 10 array is 99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(np.where(np.isin(a,np.intersect1d(a,b)) == True),np.where(np.isin(b,np.intersect1d(a,b)) == True)))

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names!= 'Will'])

[[-0.72151865  0.71834909  0.18295687 -1.76723243]
 [ 1.90528856 -0.3699398   0.00222805  0.79328017]
 [ 0.25410601  0.50568198 -0.23983561 -0.75653584]
 [ 1.31575468 -1.71825285 -0.80085112  0.14794074]
 [ 0.01892386 -0.28103527 -0.83382747  1.42910096]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
data[mask]


array([[ 0.23039457,  0.53340047,  0.60573478,  0.53990527],
       [ 1.01155014,  1.53045934, -0.96796073,  0.12984035]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [62]:
random_array = np.random.uniform(1,15,size=(5,3))
print(random_array)

[[ 1.14712131  4.31463569 14.87234724]
 [ 6.52002884 11.79847169  5.31554213]
 [ 1.0744642  12.91793389 13.23364248]
 [ 5.40089251  8.11260166 10.99570112]
 [ 2.03949506  6.08283059  8.58560124]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [64]:
random_array2 = np.random.uniform(1,16,size=(2,2,4))
print(random_array2)

[[[11.09863362 14.11331009 12.81143051  1.38537779]
  [ 9.28517138 12.24190465  7.3455669  10.24771149]]

 [[12.47940996  7.80153365  3.91694696  4.70100597]
  [ 3.64473127  7.82758901 15.50502264 12.97244575]]]


33. Swap axes of the array you created in Question 32

In [66]:
print(np.swapaxes(random_array2, 1, 0))


[[[11.09863362 14.11331009 12.81143051  1.38537779]
  [12.47940996  7.80153365  3.91694696  4.70100597]]

 [[ 9.28517138 12.24190465  7.3455669  10.24771149]
  [ 3.64473127  7.82758901 15.50502264 12.97244575]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [69]:
_array = np.random.uniform(0.1,0.27,size=(10))
sqrt_array =np.sqrt(_array)
sqrt_array[sqrt_array<0.5] = 0
print(sqrt_array)


[0.51011768 0.         0.         0.         0.         0.51055052
 0.         0.50052476 0.         0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [71]:
array1 = np.random.randint(0,12,size=10)
print(array1)
array2 = np.random.randint(0,12,size=10)
print(array2)
print('Maximum values {0}'.format(np.maximum(array1,array2)))

[ 2  5  7 11 11  8  7  6  0  1]
[ 7  1  8  0  5  6  4 11  2  2]
Maximum values [ 7  5  8 11 11  8  7 11  2  2]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [72]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [73]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))


[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [74]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
w = np.delete(sampleArray,1,1)
print(np.insert(w,1, newColumn, axis=1))


[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [58]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [75]:
random_matrix = np.random.randint(0,10,size=(2,10))
print(random_matrix)
print(np.cumsum(random_matrix))

[[5 7 6 7 8 8 3 8 3 4]
 [9 6 6 9 1 1 3 1 6 2]]
[  5  12  18  25  33  41  44  52  55  59  68  74  80  89  90  91  94  95
 101 103]
