# Numpy_Assignment_2::

In [31]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
np.arange(0,10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [33]:
array1 = np.arange(0,10).reshape(2,-1)
array2 = np.ones([2,5],dtype=np.int32)
np.vstack((array1,array2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [34]:
array1 = np.arange(0,10).reshape(2,-1)
array2 = np.ones([2,5],dtype=np.int32)
np.hstack((array1,array2))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [65]:
array1 = np.arange(0,10).reshape(2,-1)
print(array1.ravel())

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [67]:
array1 = np.arange(0,15).reshape(5,3)
print(array1.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [37]:
one_dimn = np.arange(0,15)
second_dimn = one_dimn.reshape(5,3)
print(second_dimn)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [38]:
five_x_five = np.arange(0,25).reshape(5,5)
np.square(five_x_five)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [39]:
five_x_six = np.arange(0,30).reshape(5,6)
print(np.mean(five_x_six))

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [40]:
print(np.std(five_x_six))

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [41]:
print(np.median(five_x_six))

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [68]:
print(np.transpose(five_x_six))

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [69]:
four_x_four  = np.random.randint(0,100,size=(4,4))
print(np.sum(np.diag(four_x_four)))

71


## Question:13

### Find the determinant of the previous array in Q12?

In [70]:
print(np.linalg.det(four_x_four))

1162216.000000003


## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
arr = np.random.randint(0,100,size=20)
print("5th percentile of array is {0}".format(np.percentile(arr,5)))
print("9th percentile of array is {0}".format(np.percentile(arr,95)))

5th percentile of array is 5.85
9th percentile of array is 84.30000000000001


## Question:15

### How to find if a given array has any null values?

In [46]:
arr=np.array([1,2,3,4,5,6,np.nan])
print(True in np.isnan(arr))

True
